<?php

use Illuminate\Database\Seeder;

class CardsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $card=new App\Card;
      $card->title='My first new card generated by Seeder';
      $card->body='Card body content: blabla .... by Seeder';
      $card->save();
    }
}
